import { Roboto } from "next/font/google";
import "@/styles/global.css";
import "@/styles/reset.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

const roboto = Roboto({ subsets: ["latin"], weight: "300" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.className}>
      <body className="container">
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
